### ISSUE TITLE
UndefVarError: tojson not defined

### ISSUE THREAD

**Issue by eahenle** [gdalle/PlutoProfile.jl#5]
It seems the `ProfileCanvas` package changed their API, removing the `tojson` method.  As such, `@plutoprofview` errors out.

**Comment by eahenle** [comment]
Ah, I see.  The latest version on the main branch addresses this, but is not registered on the package registry.

**Comment by gdalle** [comment]
Yeah sorry. I kind of gave up on this because ProfileCanvas alone is much easier. I'm not even sure the version on main actually works

**Comment by eahenle** [comment]
Ah, I see.  FWIW, the main branch version does work (or, rather, v0.3.2 works if you pin `ProfileCanvas` to v0.1.0) and it works very nicely.  Preferable to `ProfileCanvas` at their most recent version, in fact.

Any interest in making a PR to `ProfileCanvas` to get the `@plutoprofview` filtered view integrated there?

**Comment by gdalle** [comment]
Glad to know that! I'll ask the ProfileCanvas dev how he would feel about that, joining efforts would probably make sense, especially since the `@plutoprofview` macro doesn't add more dependencies.

**Comment by gdalle** [comment]
https://github.com/pfitzseb/ProfileCanvas.jl/issues/14
